### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Wataru-Ki** [Wataru-Ki/furima-30538#10]
# URL
https://furima-30538.herokuapp.com/
# ベーシック認証
ID = admin
Password = 2222
# 出品者用のメールアドレスとパスワード
メールアドレス = o@asd
パスワード = watarumax1
# 購入者用のメールアドレスとパスワード
メールアドレス = o@outlook.jp
パスワード = watarumax1
# 購入用カードの番号・期限・セキュリティコード
番号 = 4242424242424242
期限 = 3/23
セキュリティコード = 123

**Comment by snkw-works** [comment]
北野さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**ユーザー管理機能**
ユーザー新規登録にて空もしくは無効な値を入力して登録する時に**エラーメッセージを表示**させましょう。
（現在は登録は出来ませんがエラーメッセージが出力されません）

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Wataru-Ki** [comment]
確認ありがとうございます！
不備を解消しもう一度herokuへ反映させましたのでお手数ですが確認お願いします。
期限手前での提出で申し訳ありません

**Comment by mo1015** [comment]
北野さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by Wataru-Ki** [comment]
ありがとうございます！
